name: CI

env:
  DB_HOST: mysql
  DB_PORT: 3306
  DB_NAME: labo05_db
  DB_USER: labo05
  DB_PASS: labo05
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_DB: 0
  PYTHONPATH: src

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: self-hosted

    steps:
      - name: Nettoyer le workspace
        run: |
          sudo rm -rf ${{ github.workspace }}/* || true
          sudo rm -rf ${{ github.workspace }}/.* || true
        continue-on-error: true

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Stop existing MySQL and Redis containers
        run: |
          docker ps -q --filter "ancestor=mysql:8" | xargs -r docker stop
          docker ps -q --filter "ancestor=redis:7" | xargs -r docker stop

      - name: Créer le réseau labo05-network si besoin
        run: docker network create labo05-network || true

      - name: Démarrer BD
        run: |
          docker compose up -d mysql redis --wait
      
      #- name: Exécuter les tests
        #working-directory: src
        #env:
          #REDIS_HOST: localhost
          #DB_HOST: localhost
        #run: |
          #python -m pytest
    
  deploy:
    runs-on: self-hosted
    needs: tests
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
      - name: Nettoyer le workspace
        run: |
          sudo rm -rf ${{ github.workspace }}/* || true
          sudo rm -rf ${{ github.workspace }}/.* || true
        continue-on-error: true

      - name: Checkout dépot
        uses: actions/checkout@v4

      - name: Déploiement Docker
        run: docker compose --profile full up -d --build --remove-orphans --wait


    


  

